# Site settings
title: Daniil Demchenko
tag_text: Daniil Demchenko
description: This it personal website Daniil Demchenko

# Build settings
url: https://daniil.me   # with the https protocol
enforce_ssl: daniil.me   # without any protocol
repository: "DaniilDem/DaniilDem.github.io"
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
